### ISSUE TITLE
Reward in LEXA

### ISSUE THREAD

**Issue by Alvin-pc** [orybkin/lexa#10]
In the code, it seems to me that for reward shaping you are not making use of the images, but the actual coordinates(qpos).
```
lexa/lexa-benchmark/envs/dmc.py
  def _compute_reward(self, goal_idx, pose):
    task_type = self.task_type
    ex = self.get_excluded_qpos()
    distance = self.goals[goal_idx] - self._env.physics.data.qpos
    distance = np.linalg.norm(distance) - np.linalg.norm(distance[ex])
    reward = -distance
```
This make me confused. If you have access to the actual states and not just images, why bother with visual info learning?
Let me know if I am missing something!

**Comment by orybkin** [comment]
The agent does not use environment rewards

**Comment by Alvin-pc** [comment]
I think i misunderstood the code. I think, the environment created is being used as a benchmark to determine success.
The _gc_reward, i beleive is used to generate the reward to be used by lexa.

Any thoughts on why some goals succeed while others don't upon evaluation? What do you mean when you say a particular goal(task) is hard?
