### ISSUE TITLE
Issue at training: Tensor had Inf values

### ISSUE THREAD

**Issue by lucys0** [orybkin/lexa#2]
Hi! I'm trying to run LEXA, but I ran into the following issues:
1. `ensemble_loss: Tensor had Inf values`. When I ran `python train.py --configs defaults lexa_temporal --task kitchen --logdir logdir`, it trained for 1 step, and then after ~10 minutes (without any other ouput) it reported back the following error:
![Screen Shot 2022-02-15 at 9 48 04 PM](https://user-images.githubusercontent.com/55330385/154209459-b17ffc2b-375c-47dd-813b-4f8324ecccdc.png)

Same for `lexa_cosine` and `diayn` on `kitchen`.

2. Shape mismatch. It happened for `lexa_temporal` on `dmc_walker_walk` and `dmc_quadruped_run`.
![Screen Shot 2022-02-15 at 9 54 38 PM](https://user-images.githubusercontent.com/55330385/154209634-266cca57-67fc-4c3a-b176-2d4ffa30e961.png)
![Screen Shot 2022-02-15 at 9 55 11 PM](https://user-images.githubusercontent.com/55330385/154209642-b7ad4052-f952-4e1a-9dd8-acbbcb19ef60.png)

3. Param shape mismatch. Only happened for `python train.py --configs defaults ddl --task kitchen --logdir logdir`
![Screen Shot 2022-02-15 at 9 56 41 PM](https://user-images.githubusercontent.com/55330385/154209668-50a7d882-05c4-4d1f-b965-1e0ebe174c5c.png)

My setup generally follows the instruction in README. However, since I'm using a new version of mujoco (`mujoco-2.1.1`), I had to use `python==3.7`, `mujoco-py==2.1.2.14`, and `dm-control==0.0.425341097`.
The rest of packages (including `tensorflow==2.4.0`) are kept the same.

This is a complete list of my packages:
![Screen Shot 2022-02-15 at 9 58 53 PM](https://user-images.githubusercontent.com/55330385/154209698-6408dca6-f494-44dc-8659-22ba0881963f.png)

![Screen Shot 2022-02-15 at 9 59 55 PM](https://user-images.githubusercontent.com/55330385/154209712-9b4d92a7-3f3e-4a3a-a312-0ecd5269b30d.png)

Other specifications:
Ubuntu 18.04
CUDA 11.3

Thanks in advance!

**Comment by russellmendonca** [comment]
Hi, thanks for reaching out! I redid the setup to make sure, and I'm able to run the code without any issues. I am however using mujoco200, and this is probably causing the issue for you. Can you try to setup with mujoco200 ? (you shouldn't need to change the versions of packages in the environment.yml file.)

**Comment by lucys0** [comment]
Thanks for the reply! Yes, when I switched to mujoco200, the errors went away. It's running now. Thanks a lot!
