### ISSUE TITLE
No Envs.py module?

### ISSUE THREAD

**Issue by balloch** [orybkin/lexa#4]
I might be totally missing something, and if so I apologize, but I don't see any "envs.py" module that would contain classes like:
```
KitchenEnv
RoboBinEnv
DmcEnv
MultiplexedEnv
PadAction
```
etc.

Was it in a previous commit? Are we supposed to be getting it from another library? I noticed that Dreamer has something similar (https://github.com/danijar/dreamerv2/blob/main/dreamerv2/common/envs.py) but the class names are different. Any suggestions?

**Comment by orybkin** [comment]
The environments are in a separate repo: https://github.com/orybkin/lexa-benchmark
