### ISSUE TITLE
Inquiry about WM gradient heads

### ISSUE THREAD

**Issue by hany606** [orybkin/lexa#5]
Thank you a lot for sharing the codes!

I was curious about [grad_heads in configs.yaml ](https://github.com/orybkin/lexa/blob/19631de56ccb75907b4eb05ef838fdd4e24475a4/lexa/configs.yaml#L42), it has a reward head and this is training with the world model without any stopping for the gradients ([here](https://github.com/orybkin/lexa/blob/19631de56ccb75907b4eb05ef838fdd4e24475a4/lexa/gcdreamer_wm.py#L51-L52)). 

Is not it affecting the world model training in that sense? Maybe, I am missing something about the reward value in `data` dictionary

If yes, then it should be only `grad_heads: ['image']`, right?

Note: I am emphasising about configs related to lexa_cosine or lexa_temproal

**Comment by orybkin** [comment]
Thank you for noting this. There is an old error in the config I forgot to fix. The results in the paper are reproducible with grad_heads: ['image']. I have updated the config now.

**Comment by hany606** [comment]
Thank you so much for your fast reply!
