### ISSUE TITLE
Inquiry about robokitchen success rate

### ISSUE THREAD

**Issue by KSB21ST** [orybkin/lexa#7]
Hello,
I was running the codebase and I had some questions:
In the code, there are several metrics logged during evaluation,
and one of them is 'eval/final_success_all_objects',
another one is 'eval/mean_success_all_objects'.

Can I ask which one of the evaluation metrics was used to draw Figure A.5 in the paper?
Thank you in advance!

![image](https://github.com/orybkin/lexa/assets/58674914/d5674229-bf71-4d15-b5ed-62005fd4d341)

**Comment by orybkin** [comment]
I think the code most likely uses more than these 12 tasks. You would have to manually average these 12. Use the final success not the mean success.

**Comment by KSB21ST** [comment]
Aha, okay! Thank you for the reply!
