### ISSUE TITLE
Question about config.yaml

### ISSUE THREAD

**Issue by Dongyeongkim** [orybkin/lexa#8]
Hello,

First of all, thank you for your fabulous work in unsupervised RL.

I have a question on config.yaml,

in line 22, 'time_limit' is 150 in RoboYoga(dmc_walker_walk) as following:
https://github.com/orybkin/lexa/blob/f9cb0e5fe7213b25d8eceda62f5b51c56acc889b/lexa/configs.yaml#L22

But in the [paper](https://arxiv.org/pdf/2110.09514.pdf), it is written as 1000 as episode length,("...The episode length is 150 for RoboBin and RoboKitchen and 1000 for RoboYoga.") in Appendix section A, environment details. 

Can you clarify which configuration is right setting?

many thanks,

Kind Regards,

Dongyeong Kim

**Comment by orybkin** [comment]
Ah yes sorry, you need to specify the time limit for DMC: --time_limit 1000. Fixed this.

**Comment by Dongyeongkim** [comment]
Hello,

Thank you for fast reply!

many thanks,

Kind Regards, 

Dongyeong Kim
