### ISSUE TITLE
Issue at training in kitchen enviroment

### ISSUE THREAD

**Issue by gianluca-cioccolini** [orybkin/lexa#9]
Hi. I am trying to run LEXA in the kitchen environment  using the following command: 
```bash
python train.py --configs defaults lexa_temporal --task kitchen --logdir log 
```

I have encountered the following error:
![image](https://github.com/orybkin/lexa/assets/131887875/e60740fc-39e5-49ff-a57a-b380db23dfd9)
I am using `python 3.6.12`, `mujoco-py 2.0.2.10`, `dm-control 0.0.364896371` and `tensorflow 2.4.0`.

How can I proceed to resolve this issue?
Thanks in advance!

**Comment by orybkin** [comment]
Strange. I would expect this to be a mujoco version issue. Make sure you are using legacy mujoco. Other than that you can try to debug what's happening, it looks like the state or action dimension is wrong for some reason.

**Comment by gianluca-cioccolini** [comment]
Thank you for your response! I've checked and confirmed that I'm using the legacy version of MuJoCo. Regarding the state or action dimension issue, the dataset expects 6 dimensions for the actions, while in my case, I have 7 dimensions.

**Comment by gianluca-cioccolini** [comment]
I managed to solve the problem. Previously, I had run the dmc_walker_walk task and forgot to change the --logdir argument when I ran the task kitchen. Thanks again for your help!
